# Generated by Django 5.0.7 on 2024-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
